// Danh sách dữ liệu tĩnh chuẩn từ VietQR API v2 (65 ngân hàng) để đảm bảo luôn chạy được cả khi offline
export const VIETQR_BANKS_DATA = [
  {
    code: 'ICB',
    name: 'Ngân hàng TMCP Công thương Việt Nam',
    shortName: 'VietinBank',
    bin: '970415',
    logo: 'https://cdn.vietqr.io/img/ICB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'ICBVVNVX',
    displayOrder: 1,
  },
  {
    code: 'VCB',
    name: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
    shortName: 'Vietcombank',
    bin: '970436',
    logo: 'https://cdn.vietqr.io/img/VCB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'BFTVVNVX',
    displayOrder: 2,
  },
  {
    code: 'BIDV',
    name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    shortName: 'BIDV',
    bin: '970418',
    logo: 'https://cdn.vietqr.io/img/BIDV.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'BIDVVNVX',
    displayOrder: 3,
  },
  {
    code: 'MB',
    name: 'Ngân hàng TMCP Quân đội',
    shortName: 'MBBank',
    bin: '970422',
    logo: 'https://cdn.vietqr.io/img/MB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'MSCBVNVX',
    displayOrder: 4,
  },
  {
    code: 'TCB',
    name: 'Ngân hàng TMCP Kỹ thương Việt Nam',
    shortName: 'Techcombank',
    bin: '970407',
    logo: 'https://cdn.vietqr.io/img/TCB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'VTCBVNVX',
    displayOrder: 5,
  },
  {
    code: 'ACB',
    name: 'Ngân hàng TMCP Á Châu',
    shortName: 'ACB',
    bin: '970416',
    logo: 'https://cdn.vietqr.io/img/ACB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'ASCBVNVX',
    displayOrder: 6,
  },
  {
    code: 'VPB',
    name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    shortName: 'VPBank',
    bin: '970432',
    logo: 'https://cdn.vietqr.io/img/VPB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'VPBKVNVX',
    displayOrder: 7,
  },
  {
    code: 'TPB',
    name: 'Ngân hàng TMCP Tiên Phong',
    shortName: 'TPBank',
    bin: '970423',
    logo: 'https://cdn.vietqr.io/img/TPB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'TPBVVNVX',
    displayOrder: 8,
  },
  {
    code: 'STB',
    name: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    shortName: 'Sacombank',
    bin: '970403',
    logo: 'https://cdn.vietqr.io/img/STB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'SGTTVNVX',
    displayOrder: 9,
  },
  {
    code: 'HDB',
    name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh',
    shortName: 'HDBank',
    bin: '970437',
    logo: 'https://cdn.vietqr.io/img/HDB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'HDBCVNVX',
    displayOrder: 10,
  },
  {
    code: 'VBA',
    name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    shortName: 'Agribank',
    bin: '970405',
    logo: 'https://cdn.vietqr.io/img/VBA.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'VBAAVNVX',
    displayOrder: 11,
  },
  {
    code: 'VIB',
    name: 'Ngân hàng TMCP Quốc tế Việt Nam',
    shortName: 'VIB',
    bin: '970441',
    logo: 'https://cdn.vietqr.io/img/VIB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'VNIBVNVX',
    displayOrder: 12,
  },
  {
    code: 'SHB',
    name: 'Ngân hàng TMCP Sài Gòn - Hà Nội',
    shortName: 'SHB',
    bin: '970443',
    logo: 'https://cdn.vietqr.io/img/SHB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'SHBAVNVX',
    displayOrder: 13,
  },
  {
    code: 'MSB',
    name: 'Ngân hàng TMCP Hàng Hải Việt Nam',
    shortName: 'MSB',
    bin: '970426',
    logo: 'https://cdn.vietqr.io/img/MSB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'MCOBVNVX',
    displayOrder: 14,
  },
  {
    code: 'OCB',
    name: 'Ngân hàng TMCP Phương Đông',
    shortName: 'OCB',
    bin: '970448',
    logo: 'https://cdn.vietqr.io/img/OCB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'ORCOVNVX',
    displayOrder: 15,
  },
  {
    code: 'LPB',
    name: 'Ngân hàng TMCP Lộc Phát Việt Nam',
    shortName: 'LPBank',
    bin: '970449',
    logo: 'https://cdn.vietqr.io/img/LPB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'LVBKVNVX',
    displayOrder: 16,
  },
  {
    code: 'SEAB',
    name: 'Ngân hàng TMCP Đông Nam Á',
    shortName: 'SeABank',
    bin: '970440',
    logo: 'https://cdn.vietqr.io/img/SEAB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'SEAVVNVX',
    displayOrder: 17,
  },
  {
    code: 'EIB',
    name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam',
    shortName: 'Eximbank',
    bin: '970431',
    logo: 'https://cdn.vietqr.io/img/EIB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'EBVIVNVX',
    displayOrder: 18,
  },
  {
    code: 'TIMO',
    name: 'Ngân hàng số Timo by Ban Viet Bank',
    shortName: 'Timo',
    bin: '963388',
    logo: 'https://vietqr.net/portal-service/resources/icons/TIMO.png',
    transferSupported: true,
    lookupSupported: false,
    swiftCode: null,
    displayOrder: 19,
  },
  {
    code: 'CAKE',
    name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank',
    shortName: 'CAKE',
    bin: '546034',
    logo: 'https://cdn.vietqr.io/img/CAKE.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 20,
  },
  {
    code: 'UBANK',
    name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank',
    shortName: 'Ubank',
    bin: '546035',
    logo: 'https://cdn.vietqr.io/img/UBANK.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 21,
  },
  {
    code: 'MOMO',
    name: 'CTCP Dịch Vụ Di Động Trực Tuyến',
    shortName: 'MoMo',
    bin: '971025',
    logo: 'https://cdn.vietqr.io/img/momo.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 22,
  },
  {
    code: 'VTLMONEY',
    name: 'Tổng Công ty Dịch vụ số Viettel (Viettel Money)',
    shortName: 'ViettelMoney',
    bin: '971005',
    logo: 'https://cdn.vietqr.io/img/VIETTELMONEY.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 23,
  },
  {
    code: 'VNPTMONEY',
    name: 'VNPT Money',
    shortName: 'VNPTMoney',
    bin: '971011',
    logo: 'https://cdn.vietqr.io/img/VNPTMONEY.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 24,
  },
  {
    code: 'VCCB',
    name: 'Ngân hàng TMCP Bản Việt (BVBank)',
    shortName: 'VietCapitalBank',
    bin: '970454',
    logo: 'https://cdn.vietqr.io/img/VCCB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'VCBCVNVX',
    displayOrder: 25,
  },
  {
    code: 'SCB',
    name: 'Ngân hàng TMCP Sài Gòn',
    shortName: 'SCB',
    bin: '970429',
    logo: 'https://cdn.vietqr.io/img/SCB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'SACLVNVX',
    displayOrder: 26,
  },
  {
    code: 'SGICB',
    name: 'Ngân hàng TMCP Sài Gòn Công Thương',
    shortName: 'SaigonBank',
    bin: '970400',
    logo: 'https://cdn.vietqr.io/img/SGICB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'SBITVNVX',
    displayOrder: 27,
  },
  {
    code: 'BAB',
    name: 'Ngân hàng TMCP Bắc Á',
    shortName: 'BacABank',
    bin: '970409',
    logo: 'https://cdn.vietqr.io/img/BAB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'NASCVNVX',
    displayOrder: 28,
  },
  {
    code: 'PVCB',
    name: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    shortName: 'PVcomBank',
    bin: '970412',
    logo: 'https://cdn.vietqr.io/img/PVCB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'WBVNVNVX',
    displayOrder: 29,
  },
  {
    code: 'NCB',
    name: 'Ngân hàng TMCP Quốc Dân',
    shortName: 'NCB',
    bin: '970419',
    logo: 'https://cdn.vietqr.io/img/NCB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'NVBAVNVX',
    displayOrder: 30,
  },
  {
    code: 'SHBVN',
    name: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
    shortName: 'ShinhanBank',
    bin: '970424',
    logo: 'https://cdn.vietqr.io/img/SHBVN.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'SHBKVNVX',
    displayOrder: 31,
  },
  {
    code: 'ABB',
    name: 'Ngân hàng TMCP An Bình',
    shortName: 'ABBANK',
    bin: '970425',
    logo: 'https://cdn.vietqr.io/img/ABB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'ABBKVNVX',
    displayOrder: 32,
  },
  {
    code: 'VAB',
    name: 'Ngân hàng TMCP Việt Á',
    shortName: 'VietABank',
    bin: '970427',
    logo: 'https://cdn.vietqr.io/img/VAB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'VNACVNVX',
    displayOrder: 33,
  },
  {
    code: 'NAB',
    name: 'Ngân hàng TMCP Nam Á',
    shortName: 'NamABank',
    bin: '970428',
    logo: 'https://cdn.vietqr.io/img/NAB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'NAMAVNVX',
    displayOrder: 34,
  },
  {
    code: 'PGB',
    name: 'Ngân hàng TMCP Thịnh vượng và Phát triển',
    shortName: 'PGBank',
    bin: '970430',
    logo: 'https://cdn.vietqr.io/img/PGB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'PGBLVNVX',
    displayOrder: 35,
  },
  {
    code: 'VIETBANK',
    name: 'Ngân hàng TMCP Việt Nam Thương Tín',
    shortName: 'VietBank',
    bin: '970433',
    logo: 'https://cdn.vietqr.io/img/VIETBANK.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'VNTTVNVX',
    displayOrder: 36,
  },
  {
    code: 'BVB',
    name: 'Ngân hàng TMCP Bảo Việt',
    shortName: 'BaoVietBank',
    bin: '970438',
    logo: 'https://cdn.vietqr.io/img/BVB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'BVBVVNVX',
    displayOrder: 37,
  },
  {
    code: 'COOPBANK',
    name: 'Ngân hàng Hợp tác xã Việt Nam',
    shortName: 'COOPBANK',
    bin: '970446',
    logo: 'https://cdn.vietqr.io/img/COOPBANK.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 38,
  },
  {
    code: 'KLB',
    name: 'Ngân hàng TMCP Kiên Long',
    shortName: 'KienLongBank',
    bin: '970452',
    logo: 'https://cdn.vietqr.io/img/KLB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'KLBKVNVX',
    displayOrder: 39,
  },
  {
    code: 'KBANK',
    name: 'Ngân hàng Đại chúng TNHH Kasikornbank',
    shortName: 'KBank',
    bin: '668888',
    logo: 'https://cdn.vietqr.io/img/KBANK.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'KASIVNVX',
    displayOrder: 40,
  },
  {
    code: 'WVN',
    name: 'Ngân hàng TNHH MTV Woori Việt Nam',
    shortName: 'Woori',
    bin: '970457',
    logo: 'https://cdn.vietqr.io/img/WVN.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 41,
  },
  {
    code: 'VRB',
    name: 'Ngân hàng Liên doanh Việt - Nga',
    shortName: 'VRB',
    bin: '970421',
    logo: 'https://cdn.vietqr.io/img/VRB.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 42,
  },
  {
    code: 'HSBC',
    name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)',
    shortName: 'HSBC',
    bin: '458761',
    logo: 'https://cdn.vietqr.io/img/HSBC.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: 'HSBCVNVX',
    displayOrder: 43,
  },
  {
    code: 'CBB',
    name: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam',
    shortName: 'CBBank',
    bin: '970444',
    logo: 'https://cdn.vietqr.io/img/CBB.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: 'GTBAVNVX',
    displayOrder: 44,
  },
  {
    code: 'CIMB',
    name: 'Ngân hàng TNHH MTV CIMB Việt Nam',
    shortName: 'CIMB',
    bin: '422589',
    logo: 'https://cdn.vietqr.io/img/CIMB.png',
    transferSupported: true,
    lookupSupported: true,
    swiftCode: 'CIBBVNVN',
    displayOrder: 45,
  },
  {
    code: 'GPB',
    name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu',
    shortName: 'GPBank',
    bin: '970408',
    logo: 'https://cdn.vietqr.io/img/GPB.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: 'GBNKVNVX',
    displayOrder: 46,
  },
  {
    code: 'IVB',
    name: 'Ngân hàng TNHH Indovina',
    shortName: 'IndovinaBank',
    bin: '970434',
    logo: 'https://cdn.vietqr.io/img/IVB.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 47,
  },
  {
    code: 'UOB',
    name: 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh',
    shortName: 'UnitedOverseas',
    bin: '970458',
    logo: 'https://cdn.vietqr.io/img/UOB.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: null,
    displayOrder: 48,
  },
  {
    code: 'SCVN',
    name: 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam',
    shortName: 'StandardChartered',
    bin: '970410',
    logo: 'https://cdn.vietqr.io/img/SCVN.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: 'SCBLVNVX',
    displayOrder: 49,
  },
  {
    code: 'PBVN',
    name: 'Ngân hàng TNHH MTV Public Việt Nam',
    shortName: 'PublicBank',
    bin: '970439',
    logo: 'https://cdn.vietqr.io/img/PBVN.png',
    transferSupported: false,
    lookupSupported: true,
    swiftCode: 'VIDPVNVX',
    displayOrder: 50,
  },
];
